More configure changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1669,22 +1669,46 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+if ! test -z "${SNAKECHARMR_PYTHONPATH}"; then
+  PYTHONPATH=${SNAKECHARMR_PYTHONPATH}
+elif test -z "${PYTHONPATH}"; then
+  echo "WARNING: it might be necessary to correctly set PYTHONPATH for installation to work"
+  echo "References:"
+  echo "  https://docs.python.org/2/using/cmdline.html#environment-variables"
+  echo "  https://docs.python.org/3/using/cmdline.html#environment-variables for more information"
+fi
+echo "PYTHONPATH=${PYTHONPATH}"
+
 PYTHON_CONFIG=python${SNAKECHARMR_PYTHON_VERSION}-config
 command -v ${PYTHON_CONFIG} >/dev/null 2>&1 || { echo "Cannot find command '${PYTHON_CONFIG}'. Aborting."; exit 1; }
-echo Using python config ${PYTHON_CONFIG}
+echo "Using Python config ${PYTHON_CONFIG}"
 
-PYTHON_INTERPRETER=`${PYTHON_CONFIG} --prefix`/bin/python
-echo Using python interpreter ${PYTHON_CONFIG}
+if test -n "${SNAKECHARMR_PYTHON_INTERPRETER}"; then
+  command -v ${SNAKECHARMR_PYTHON_INTERPRETER} >/dev/null 2>&1 || { echo "Cannot find command '${SNAKECHARMR_PYTHON_INTERPRETER}'. Aborting."; exit 1; }
+elif command -v python${SNAKECHARMR_PYTHON_VERSION} --version  >/dev/null 2>&1; then
+  SNAKECHARMR_PYTHON_INTERPRETER=python${SNAKECHARMR_PYTHON_VERSION}
+elif command -v `${PYTHON_CONFIG} --prefix`/bin/python${SNAKECHARMR_PYTHON_VERSION} --version  >/dev/null 2>&1; then
+  SNAKECHARMR_PYTHON_INTERPRETER=`${PYTHON_CONFIG} --prefix`/bin/python${SNAKECHARMR_PYTHON_VERSION}
+elif command -v `${PYTHON_CONFIG} --prefix`/bin/python --version  >/dev/null 2>&1; then
+  SNAKECHARMR_PYTHON_INTERPRETER=`${PYTHON_CONFIG} --prefix`/bin/python
+elif command -v python --version  >/dev/null 2>&1; then
+  SNAKECHARMR_PYTHON_INTERPRETER=python
+fi
+echo "Using Python interpreter ${SNAKECHARMR_PYTHON_INTERPRETER}"
 
 # find user defined python version, if set
 if test -z "${SNAKECHARMR_PYTHON_VERSION}"; then
-  command -v ${PYTHON_INTERPRETER} >/dev/null 2>&1 || { echo "Cannot find command '${PYTHON_INTERPRETER}'. Aborting."; exit 1; }
-  SNAKECHARMR_PYTHON_VERSION=`python -c "import sys; print(str(sys.version_info.major) + '.' + str(sys.version_info.minor))"`
-  echo Found Python version ${SNAKECHARMR_PYTHON_VERSION}...
+  SNAKECHARMR_PYTHON_VERSION=`${SNAKECHARMR_PYTHON_INTERPRETER} -c "import sys; print(str(sys.version_info.major) + '.' + str(sys.version_info.minor))"`
 fi
+echo "Using Python version ${SNAKECHARMR_PYTHON_VERSION}"
 
-PKG_LIBS=`$PYTHON_CONFIG --ldflags`
-PKG_CPPFLAGS=`$PYTHON_CONFIG --includes`
+${PYTHON_CONFIG} --ldflags
+PKG_LIBS=`${PYTHON_CONFIG} --ldflags`
+echo PKG_LIBS=$PKG_LIBS
+
+PKG_CPPFLAGS=`${PYTHON_CONFIG} --includes`
+echo PKG_CPPFLAGS=$PKG_CPPFLAGS
+
 #PKG_CPPFLAGS+=" -D PYTHONLIBFILE=\\\"libpython${SNAKECHARMR_PYTHON_VERSION}.so\\\""
 
 
